### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by susho** [alecthomas/template#3]
Hello @alecthomas

This project is missing a license.
Please add a license to this project, I am planning to use this.

Thank you.

**Comment by alecthomas** [comment]
Hi @susho ... as Go 1.6 now supports [whitespace elision](https://golang.org/pkg/text/template/#hdr-Text_and_spaces), I won't be making any further changes to this package and will probably delete it soon.

**Comment by alecthomas** [comment]
I should rephrase: this will not be deleted until it is no longer used.

**Comment by onlyjob** [comment]
In this case we really need a `LICENSE`. :)

Please reopen.

**Comment by onlyjob** [comment]
FYI @petercolberg.
