### ISSUE TITLE
Add LICENSE?

### ISSUE THREAD

**Issue by ches** [alecthomas/template#4]
Hi Alec,

I know this almost entirely a copy of source code from Go—the files have leading comments referencing the `LICENSE` file. Assuming you release it under the same license, could you add the `LICENSE` file to the project for sake of legal formalities? Since it's a dependency of `kingpin` I need to dot the "i"s here.

Thanks!

**Comment by alecthomas** [comment]
👍

**Comment by ches** [comment]
Thanks again!

**Comment by mknecht** [comment]
@ches thx for doing that; i'm currently following the license dots for kingpin :)
